### ISSUE TITLE
Producing .xcframeworks

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#1249]
This is just a tracking issue for producing xcframeworks, since this is a common use case we should support

**Comment by mathaeus** [comment]
@keith @brentleyjones 

From what I see adding `xcframework` support was added [here](https://github.com/bazelbuild/rules_apple/commit/69670b9e27c3e1071e2a8685c1b5193f8fea9dc3)? Or am I wrong about that?

Are you planning on releasing this anytime soon?

----

I gave the whole thing a shot and I think I ran into a bug, or the thing is just not ready yet.
Anyway here's what I tried:

`WORKSPACE` file

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

... 

git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    branch = "master",
)
```

`BUILD` file
```
load("@build_bazel_rules_apple//apple:apple.bzl", "apple_xcframework")

...

apple_xcframework(
    name = "MyFramework",
    bundle_id = "com.foo.bar",
    deps = [
        ":SomeObjcDep",
        "@ios_opencv//:OpencvFramework",
    ],
    families_required = { "ios": "iphone" },
    infoplists = ["Info.plist"],
    ios = {"device": "arm64"},
    minimum_deployment_os_versions = {"ios": "14.0"},
    minimum_os_versions = {"ios": "14.0"}
)
```

I then run into that error:
```
ERROR: /private/var/tmp/_bazel_mathaeus/7daf80b34ca02d70eeaf84c8ae68b14f/external/build_bazel_rules_apple/apple/internal/xcframework_rules.bzl:326:19: name 'json' is not defined
ERROR: /private/var/tmp/_bazel_mathaeus/7daf80b34ca02d70eeaf84c8ae68b14f/external/build_bazel_rules_apple/apple/internal/xcframework_rules.bzl:390:19: name 'json' is not defined
```

Seems like it can't find the [json encoder](https://github.com/bazelbuild/rules_apple/blob/master/apple/internal/xcframework_rules.bzl#L326).

----

Please let me know if I'm on the right track here or how I could try out `apple_xcframework` (_if it's ready_).

Thanks!

**Comment by brentleyjones** [comment]
Are you using bazel 5.0? The next release will require it (which is why we haven't made a release yet, as it's still in RC).

**Comment by mathaeus** [comment]
Thanks for the quick reply @brentleyjones.

No, the project I'm trying to run has `3.7.2` in its `.bazelversion`, and from what I can see `bazelisk` was using that version therefore.

So bazel 5.0 is a requirement then for this, if I understand correctly?

**Comment by brentleyjones** [comment]
Yes. And Bazel 4.x is required for the latest release (or, that is all we tested it with, it might somehow work with 3.7.2).

**Comment by cpsauer** [comment]
Was this solved by the recent 0.33.0 release? 

(Saw "Add rule for producing xcframeworks for iOS" in the release notes)

**Comment by thii** [comment]
Partially, yes. There's still missing support for producing XCFrameworks bundling static frameworks.
