### ISSUE TITLE
ios_application fails when using provisioning_profile

### ISSUE THREAD

**Issue by ryanfitz** [bazelbuild/rules_apple#28]
I'm running latest master version of bazel and the apple rules. I have a sample application, which is setup to use a real provisioning profile for this sample app id. I'm running into the following error when attempting to build the ios_application target.

```
INFO: Found 1 target...
ERROR: /Users/fitz/Code/bazel-examples/HelloBuck/HelloBuck/BUILD:14:1: error executing shell command: 'set -e && PLIST=$(mktemp -t entitlements.plist) && trap "rm ${PLIST}" EXIT && security cms -D -i "HelloBuck/provisioning/integration_testing.mobileprovision" > ${PLIST} && /usr/libexec/PlistBuddy -...' failed: bash failed: error executing command
  (exec env - \
  /bin/bash -c 'set -e && PLIST=$(mktemp -t entitlements.plist) && trap "rm ${PLIST}" EXIT && security cms -D -i "HelloBuck/provisioning/integration_testing.mobileprovision" > ${PLIST} && /usr/libexec/PlistBuddy -x -c '\''Print Entitlements'\'' ${PLIST} > "bazel-out/local-fastbuild/bin/HelloBuck/entitlements/Peloton_entitlements.entitlements_with_variables"')

Use --sandbox_debug to see verbose messages from the sandbox.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: UNIX[Operation not permitted]
security: problem decoding
Use --strategy=ExtractAppleEntitlements=standalone to disable sandboxing for the failing actions.
WARNING: Cannot delete sandbox directory after action execution: /private/var/tmp/_bazel_fitz/eee1aeec8b965ffb8dc3e98cab7ac9b9/bazel-sandbox/9050354069223113742 (java.io.IOException: /private/var/tmp/_bazel_fitz/eee1aeec8b965ffb8dc3e98cab7ac9b9/bazel-sandbox/9050354069223113742/execroot/HelloBuck (Directory not empty)).
Target //HelloBuck:Peloton failed to build
INFO: Elapsed time: 0.497s, Critical Path: 0.43s
```

WORKSPACE
```
load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')

git_repository(
  name = "build_bazel_rules_apple",
  remote = "https://github.com/bazelbuild/rules_apple.git",
  commit = "fe6b902e0c6e17247706d8c8fdb8f83b1644cfa6"
)
```
BUILD
```
package(default_visibility = ["//visibility:public"])

licenses(["notice"])

load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
load("@build_bazel_rules_apple//apple:swift.bzl", "swift_library")

swift_library(
  name = "lib",
  srcs = glob(["*.swift"])
)

ios_application(
    name = "HelloWorld",
    bundle_id = "com.Peloton.HelloWorld",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = [":Info.plist"],
    launch_storyboard = "Resources/LaunchScreen.storyboard",
    deps = [":lib"],
    provisioning_profile = "//HelloBuck/provisioning:integration_testing.mobileprovision",
)
```

Locally when I run `security cms -D -i integration_testing.mobileprovision` it outputs on stderr `security: SecPolicySetValue: One or more parameters passed to a function were not valid.` However, it also prints out the decoded plist on stdout. This appears to be a known issue with mac os sierra.

**Comment by allevato** [comment]
Yeah, the error message emitted by `security` is a known issue that I believe we can ignore.

If you pass the recommended flag `--strategy=ExtractAppleEntitlements=standalone` to your `bazel build` command line, does that cause the build to succeed? If so, it's a simple fix to disable sandboxing for that action in the rule itself; we may need to do that if the sandbox prevents it from accessing the system keychain.

**Comment by ryanfitz** [comment]
I'm running into the same error when running build with `--strategy=ExtractAppleEntitlements=standalone`

**Comment by allevato** [comment]
Taking a closer look, I just noticed this in your application target:

```
provisioning_profile = "//HelloBuck/provisioning:integration_testing.mobileprovision"
```

Is that a copy of the testing provisioning profile from this repository? If so, that won't work—that profile is a fake one used only for the integration tests of the rules in this repository and you'll need to use a real one obtained from Apple (or, for simulator builds, you can leave the attribute off entirely).

**Comment by ryanfitz** [comment]
The name is the same as from some of the tests in this repo, however, it is a real provisioning profile from the apple dev portal configured for this app id. 

Also, it appears that `provisioning_profile` is not an optional attribute, when leaving off provisioning profile I get the following error message

```
ERROR: /Users/fitz/Code/bazel-examples/rules_apple/examples/ios/HelloWorld/BUILD:19:1: in ios_application rule //examples/ios/HelloWorld:HelloWorld:
Traceback (most recent call last):
        File "/Users/fitz/Code/bazel-examples/rules_apple/examples/ios/HelloWorld/BUILD", line 19
                ios_application(name = 'HelloWorld')
        File "/Users/fitz/Code/bazel-examples/rules_apple/apple/bundling/ios_rules.bzl", line 84, in _ios_application_impl
                bundler.run(ctx, "IosApplicationArchive", "iOS a...", <3 more arguments>)
        File "/Users/fitz/Code/bazel-examples/rules_apple/apple/bundling/bundler.bzl", line 792, in bundler.run
                _process_and_sign_archive(ctx, bundle_name, bundle_path_in_arc..., <4 more arguments>)
        File "/Users/fitz/Code/bazel-examples/rules_apple/apple/bundling/bundler.bzl", line 388, in _process_and_sign_archive
                codesigning_support.signing_command_lines(ctx, bundle_path_in_archive, entitle...)
        File "/Users/fitz/Code/bazel-examples/rules_apple/apple/bundling/codesigning_support.bzl", line 178, in codesigning_support.signing_command_lines
                fail("The provisioning_profile attrib...))
The provisioning_profile attribute must be set for device builds on this platform (ios).
ERROR: Analysis of target '//examples/ios/HelloWorld:HelloWorld' failed; build aborted.
INFO: Elapsed time: 3.235s
```

**Comment by allevato** [comment]
It should only be required for device builds only (`--ios_multi_cpus=armv7,arm64`), but if you're seeing that error for simulator builds as well, it's possible that a recent change in the code signing flow broke that. Let me investigate.

**Comment by allevato** [comment]
Yes, it looks like that's what happened. Prepping a fix.

**Comment by allevato** [comment]
I just merged in #29, which should fix the issue you're encountering for simulator builds.

I also disabled sandboxing for the entitlements extraction action; can you try a device build with your provisioning profile to see if that resolves the original issue?

**Comment by ryanfitz** [comment]
@allevato thanks for the quick turn around time. Running without a provisioning profile the builds works successfully. However, including a provisioning profile it still fails for me. Perhaps its something else I have misconfigured.

**Comment by allevato** [comment]
Hmm. I was able to duplicate the error you're seeing if I use a provisioning profile locally, except that the action involved this time in the strategy output was `ExtractAppleTeamPrefix` instead of `ExtractAppleEntitlements`, so it looks like we may have missed one. Let me see if I can knock out all of the sandboxing issues...

**Comment by allevato** [comment]
I just merged in some additional changes that I believe *should* fix your issues (based on my own testing). Can you please try again, without any additional flags?

**Comment by ryanfitz** [comment]
Latest changes on master are working for me. Thanks again

**Comment by allevato** [comment]
Glad to hear it!

Cross-referencing for posterity: Fixed by #29 and #30.
