### ISSUE TITLE
Support for swift on iOS 12.2 / XCode 10.2

### ISSUE THREAD

**Issue by jdelfino** [bazelbuild/rules_apple#371]
I'm having trouble running iOS apps built with bazel 0.23.2, rules_apple 0.14, macOS 10.14.3 after upgrading to XCode 10.2

The surface problem I'm seeing are errors like this when trying to launch the app on a simulator from (a Tulsi-generated project for) XCode: 

```This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.
2019-03-27 14:37:08.774142-0400 CanopyDev[3813:3310546] This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.
```

I see slightly more informative errors when trying to run an ios_unit_test from the command line:

```
objc[15404]: Class _TtCs18__stdlib_AtomicInt is implemented in both /Users/jdelfino/Library/Developer/CoreSimulator/Devices/DC32A664-6751-4206-B8D3-B1C2698E4E6A/data/Containers/Bundle/Application/7AFD5B16-5471-4639-A40B-68C36A72F699/CanopyDev.app/Frameworks/libswiftCore.dylib (0x10d967168) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib (0x123a65138). One of the two will be used. Which one is undefined.

... [many more similar] 
```

Something I suspect is related - with iOS 12.2, I believe Swift dylibs are now shipped with the OS. XCode 10.2 apparently no longer bundles these dylibs: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2?preferredLanguage=occ.

As a test, I hacked the rules to not include the dylibs for ios apps (https://github.com/bazelbuild/rules_apple/compare/master...ourcanopy:xcode10_2?expand=1). Both launching the app through XCode and running the unit test through the simulator work with this hack.

**Comment by keith** [comment]
This should be fixed on master of rules_apple. Can you test your case to see?

**Comment by jdelfino** [comment]
Unfortunately, it is still broken on master (a75252a00bf58e236ff41823972a53b2e04c3c0f).

**Comment by keith** [comment]
Ah yes. The problem is fixed by https://github.com/bazelbuild/bazel/issues/7830

**Comment by jdelfino** [comment]
Thanks @keith! Will keep an eye on that issue & retest when a bazel build is available.

**Comment by keith** [comment]
This can be closed, this is fixed by newer versions of bazel

**Comment by thomasvl** [comment]
Thanks
